### ISSUE TITLE
Support backoff for rate limiting

### ISSUE THREAD

**Issue by upstart-swiss** [SumoLogic/terraform-provider-sumologic#201]
One of my repositories hits rate limits and the provider isn't doing a backoff or handling it well

From a tf plan:
```
[2021-06-08T20:50:29.597Z] Error: {"id":"0H9HG-7A2K0-T5B0K","errors":[{"code":"rate.limit.exceeded","message":"API rate limit for this user has been exceeded."}]}
```

**Comment by seansain** [comment]
Thanks for bringing this up! We do actually have a rate limiter built into the provider so it's interesting that you are getting rate limited. We will look into adding backoff and retries.

**Comment by upstart-swiss** [comment]
I didn't hit it until I started working with the `content` resource type. May be related there.

**Comment by seansain** [comment]
Hmm okay. Are you running with any parallelism? Any chance you can share the debug logs or the Terraform resources you are creating?

**Comment by upstart-swiss** [comment]
Default by TF is 10, I stopped hitting timeouts when i reduced it to 2.

**Comment by upstart-swiss** [comment]
I can share details in the shared org slack channel (ask Frank Reno for access), but not via github.

**Comment by tcushman** [comment]
I have also experienced `terraform apply` failing due to rate limiting a few times.  We run multiple instances of `terraform apply` concurrently to deploy several application environments that all link to the same account in Sumologic.  We also have many applications which can be deployed concurrently.
Relying on a request scheduling mechanism, as the provider currently does, is only reliable when one client, or a predictable number of clients, are using the service.
