### ISSUE TITLE
`sumologic_folder` resource error: unexpected end of JSON input

### ISSUE THREAD

**Issue by devanbenz** [SumoLogic/terraform-provider-sumologic#317]
I am trying to use the `sumologic_folder` resource to create a folder within sumo logic to then deploy metrics dashboards. Currently, my terraform code gets caught up during the folder creation resource with the following error: 

`│ Error: unexpected end of JSON input
│ 
│   with module.sumologic.sumologic_folder.per_environment,
│   on modules/sumologic/folders.tf line 4, in resource "sumologic_folder" "per_environment":
│    4: resource "sumologic_folder" "per_environment" {`

**Comment by emichaeli** [comment]
Hey @devanbenz, thanks for reporting this issue. The fix for this (which should provide a more clear error message on what went wrong) should be rolled out in the next provider release. However, I don't have enough information to know for sure whether the fix covers your case as well based on the description here.

What I believe is happening is something along those lines of:
- You've previously created that folder with Terraform, and are now using some different credentials that do not have access to this folder
- You're using the same credentials that were used to originally create the folder, but the issuing user of those credentials do not have permissions to this folder any more (for example because the user's role changed)

Do any of the above sound right? Otherwise, it would be great if you can provide more information on how you came about running to this issue. For example, is this the first time you're using the folder resource to create it? Does it only happen for a specific folder or any folder?

**Comment by devanbenz** [comment]
I have tried with an existing folder (using my API credentials) and I have tried creating a folder. We have been using our primary administrator accounts credentials for the sumo api access keys as well. So I have tried both my account using my personal folder and with the administrator account using the admin recommended folder.

**Comment by sumovishal** [comment]
@devanbenz would be possible for you to provide us debug logs? You can enable debug logs by prepending `TF_LOG=DEBUG`to your terraform command. The logs may help us get better understanding of the issue here.

**Comment by icco** [comment]
@sumovishal could we email them? 

Deleting the folder from our (I work with @devanbenz) tf state didn't resolve the issue, but deleting the dashboards as well did, which makes me think this issue is actually unrelated to folder, and instead related to a corrupted dashboard config.

**Comment by sumovishal** [comment]
@icco yeah, email is fine. Can you email it to "vishal@sumologic.com" and "emichaeli@sumologic.com"?

**Comment by emichaeli** [comment]
Closing this issue as the "unexpected end of JSON input" error for both `folder` and `dashboard` resources was fixed in https://github.com/SumoLogic/terraform-provider-sumologic/pull/319
