### ISSUE TITLE
Terraform support for installed collectors

### ISSUE THREAD

**Issue by eambrosyupgrade** [SumoLogic/terraform-provider-sumologic#365]
### Description

In the Sumologic console I can manage existing installed collectors. I can rename, for updates to newer versions, as well as adding categories, fields, and timezones like I can with hosted collectors. However I am unable to create or manage these resources in terraform. Making things split on the management of my Sumo org's collectors.

### New or Affected Resource(s)

- sumologic_installed_collector

### Potential Terraform Configuration

```hcl
resource "sumologic_installed_collector" "collector" {
  name        = "my-collector"
  version     = "my-version"
  description = "Just testing this"
  fields  = {
    environment = "production"
  }
}
```

### References

- [Docs](https://help.sumologic.com/03Send-Data/Installed-Collectors/01About-Installed-Collectors)

**Comment by vsinghal13** [comment]
Hi, @eambrosyupgrade thanks for the request.

I have an open PR for supporting installed collectors. It needs some more work and has not been prioritized lately. Feel free to contribute to the existing PR, so that we can get the feature out as quickly as possible.
https://github.com/SumoLogic/terraform-provider-sumologic/pull/182

**Comment by vsinghal13** [comment]
this resource is available now.
